### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by hinerm** [CellProfiler/centrosome#121]
I am trying to follow the instructions [here](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29#downloading-cellprofilers-libraries-and-dependencies) on Windows 10 x64. I have:

* Installed/updated the Visual C++ 2015-2022 redist and VS C++ build tools
* Set `JAVA_HOME` and `JDK_HOME` to a Java 11 JDK
* created and activated a new conda environment with `python=3.8`
* installed `numpy` via `pip`
* `pip install -e` on [core](https://github.com/cellprofiler/core) successfully

 When I try to `pip install -e` on CellProfiler itself I get this error:

```
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_convex_hull.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_cpmorphology2.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_fastemd.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_filter.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_lapjv.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: centrosome\_lapjv.pyx:281:12: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: centrosome\_lapjv.pyx:281:18: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\hiner\AppData\Local\Temp\pip-install-g3trzzqk\centrosome_d6d57599675246b7aca138a29344b875\centrosome\_propagate.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
            heap.ptrs[child][k] = new_elem[k]
        heap.items += 1

        # restore heap invariant, all parents <= children
        while child>0:
            parent = (child + 1) / 2 - 1 # __parent(i)
                                     ^
      ------------------------------------------------------------

      centrosome\heap.pxd:148:31: Cannot assign type 'double' to 'unsigned int'
      Compiling centrosome/_propagate.pyx because it changed.
      Compiling centrosome/_convex_hull.pyx because it changed.
      Compiling centrosome/_cpmorphology2.pyx because it changed.
      Compiling centrosome/_fastemd.pyx because it changed.
      Compiling centrosome/_filter.pyx because it changed.
      Compiling centrosome/_lapjv.pyx because it changed.
      [1/6] Cythonizing centrosome/_convex_hull.pyx
      [2/6] Cythonizing centrosome/_cpmorphology2.pyx
      [3/6] Cythonizing centrosome/_fastemd.pyx
      [4/6] Cythonizing centrosome/_filter.pyx
      [5/6] Cythonizing centrosome/_lapjv.pyx
      [6/6] Cythonizing centrosome/_propagate.pyx
      Traceback (most recent call last):
        File "C:\Users\hiner\miniconda3\envs\cp-ij\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hiner\miniconda3\envs\cp-ij\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\hiner\miniconda3\envs\cp-ij\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Build\Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "C:\Users\hiner\AppData\Local\Temp\pip-build-env-cgnd7q37\normal\Lib\site-packages\Cython\Build\Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: centrosome/_propagate.pyx
      [end of output]
```

I tried cloning centrosome and building it from source and get the same issue. A few things are confusing me:

1. Why do I get `FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3)` despite [this](https://github.com/CellProfiler/centrosome/blob/b178071cff4c166ed50c7f0b4f25d34776f856d4/setup.py#L93)?
2. When I change code in `heap.pxd` and try rebuilding with `pip install -e .` why is it not seeing the code changes?
3. `heap.pxd` seems to be [using floor division](https://github.com/CellProfiler/centrosome/blob/b178071cff4c166ed50c7f0b4f25d34776f856d4/centrosome/heap.pxd#L148) correctly, so where could the compiler be getting the non-flooring division code from..?

**Comment by bethac07** [comment]
What's your cython version?

**Comment by bethac07** [comment]
And are CellProfiler/core relatively freshly pulled? This was an issue with Cython3 that should have been fixed a couple months ago...

**Comment by hinerm** [comment]
> And are CellProfiler/core relatively freshly pulled? This was an issue with Cython3 that should have been fixed a couple months ago...

oh my gosh I'm sorry.. apparently it wasn't, which is so weird because `centrosome` was a fresh clone and I went through to `git pull` everything first?! I don't know what's happening. Need more☕ I guess. It totally working when I'm up-to-date
